name: Sync to Hugging Face hub

on:
  push:
    branches: [master]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up Hugging Face remote
      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.Student_score_predictor }}  # Hugging Face Token stored in GitHub secrets
        run: |
          git remote add space https://noahgift:${HF_TOKEN}@huggingface.co/spaces/tayyubGX/Student_score_predictor

      # Push code to Hugging Face Space
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.Student_score_predictor }}  # Hugging Face Token stored in GitHub secrets
        run: |
          git push --force https://noahgift:${HF_TOKEN}@huggingface.co/spaces/tayyubGX/Student_score_predictor main
